# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/variables.json
Variables:
  com:
    axonivy:
      demo:
        anonymous_user:
          # External URL to application open space for building external links.
          # For the designer test use: http://localhost:81/~Developer-anonymous-user-demos/Developer-anonymous-user-demos/1/pro
          # For the engine test use: http://localhost/~Developer-anonymous-user-demos/Developer-anonymous-user-demos/1/pro
          baseUrl: http://localhost:81/~Developer-anonymous-user-demos/Developer-anonymous-user-demos/1/pro