shape: sequence_diagram

style.fill: transparent

classes: {
  mailtx: {
    style: {
      stroke-width: 4
      bold:true
    }
  }
}

external: "External\nUser"
internal: "Internal\nUser"

ivy: "Axon Ivy"


external -> ivy: "Register by email address"
ivy -> external: "✉ Send verification email"{
    class: mailtx
}
ivy -> external: "\"Please check your email\""
external -> ivy: "Confirm email address"
ivy -> external: "\"Your email was confirmed\""

internal -> ivy: "Open validation task"
ivy -> external: "✉ Request missing data email"{
    class: mailtx
}
ivy -> internal: ""

external -> ivy: "Submit missing data"
ivy -> external: "\"Thank you for submitting missing data\""

internal -> ivy: "Open validation task and accept"
ivy -> external: "✉ Approved email"{
    class: mailtx
}
ivy -> internal: ""
